# Generated by Django 2.2.2 on 2019-10-21 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0005_auto_20191021_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='file',
        ),
        migrations.AddField(
            model_name='userfile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
